name: Run Steampipe
on:
  push:

jobs:
  steampipe:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Steampipe Setup
        uses: turbot/steampipe-action-setup@v1
        with:
          plugin-connections: |
            connection "tf" {
              plugin = "terraform"
              paths = [ "./*.tf"]
            }
  
